<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB; // Perbaikan: Tambahkan use statement untuk DB
use Carbon\Carbon;

class BookSeeder extends Seeder
{
    public function run()
    {
        DB::table('buku')->insert([
            [
                'Judul' => 'Applied Multivariate Statistical Analysis 5th Edition',
                'Author' => 'Richard Arnold Johnson, Dean W. Wichern',
                'Sampul' => 'https://m.media-amazon.com/images/I/416EKVyhnBL.SY445_SX342.jpg',
                'Deskripsi' => 'Buku ini membahas konsep dan metode utama dalam analisis multivariat. Dikenal sebagai salah satu referensi standar dalam bidang ini, buku ini mencakup topik seperti regresi multivariat, analisis faktor, dan analisis diskriminan.',
                'Halaman' => 773,
                'Penerbit' => 'Pearson College Div',
                'Tahun' => 2002,
                'Berat' => 1384,
                'ISBN' => '9780130925534',
                'Lebar' => 7.75,
                'Panjang' => 9.5,
                'Bahasa' => 'Inggris',
                'Kategori' => 'Statistika',
                'Stok' => 15,
                'Akses' => 'Dapat dipinjam',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Judul' => 'Multivariate Data Analysis (8th Edition)',
                'Author' => 'Joseph F Hair, Barry J. Babin, Rolph E. Anderson, William C. Black',
                'Sampul' => 'https://m.media-amazon.com/images/I/81AL5LnyHlL.SL1500.jpg',
                'Deskripsi' => 'Buku ini merupakan panduan komprehensif tentang teknik-teknik analisis data multivariat, termasuk regresi berganda, analisis jalur, dan SEM (Structural Equation Modeling). Sangat berguna untuk peneliti yang bekerja dengan data yang kompleks dan besar.',
                'Halaman' => 832,
                'Penerbit' => 'Cengage Learning',
                'Tahun' => 2019,
                'Berat' => 1289,
                'ISBN' => '9789353501358',
                'Lebar' => 7.99,
                'Panjang' => 15,
                'Bahasa' => 'Inggris',
                'Kategori' => 'Statistika',
                'Stok' => 15,
                'Akses' => 'Dapat dipinjam',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Judul' => 'Concise Guide to Databases: A Practical Introduction (Undergraduate Topics in Computer Science) 2nd edition',
                'Author' => 'Konstantinos Domdouzis, Peter Lake, Paul Crowther',
                'Sampul' => 'https://m.media-amazon.com/images/I/61TPU4Mmc4L.SL1254.jpg',
                'Deskripsi' => 'Buku ini memberikan panduan singkat dan komprehensif tentang basis data, mencakup konsep-konsep dasar, tipe-tipe basis data, serta teknologi yang digunakan dalam pengelolaan data. Cocok bagi pembaca yang ingin memahami dasar-dasar sistem basis data secara cepat.',
                'Halaman' => 424,
                'Penerbit' => 'Springer',
                'Tahun' => 2021,
                'Berat' => 645,
                'ISBN' => '9783030422233',
                'Lebar' => 6.1,
                'Panjang' => 9.25,
                'Bahasa' => 'Inggris',
                'Kategori' => 'Pemrograman',
                'Stok' => 15,
                'Akses' => 'Dapat dipinjam',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Judul' => 'Data Mining: Practical Machine Learning Tools and Techniques (The Morgan Kaufmann Series in Data Management Systems) 3rd Edition',
                'Author' => 'Ian H. Witten, Eibe Frank, Mark A. Hall',
                'Sampul' => 'https://m.media-amazon.com/images/I/81sYy1D9n7L.SL1360.jpg',
                'Deskripsi' => 'Buku ini menawarkan pendekatan praktis untuk machine learning, mencakup alat dan teknik yang dapat digunakan dalam berbagai aplikasi machine learning. Cocok untuk mereka yang ingin mengaplikasikan pembelajaran mesin secara nyata menggunakan berbagai perangkat.',
                'Halaman' => 664,
                'Penerbit' => 'Morgan Kaufmann',
                'Tahun' => 2011,
                'Berat' => 1357,
                'ISBN' => '9780123748560',
                'Lebar' => 7.5,
                'Panjang' => 9.25,
                'Bahasa' => 'Inggris',
                'Kategori' => 'Pemrograman',
                'Stok' => 15,
                'Akses' => 'Dapat dipinjam',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Judul' => 'Natural Language Processing with Python',
                'Author' => 'Steven Bird, Ewan Klein, Edward Loper',
                'Sampul' => 'https://m.media-amazon.com/images/I/81Z8Ko9zszL.SL1500.jpg',
                'Deskripsi' => 'Buku ini adalah panduan praktis untuk pemrosesan bahasa alami (NLP) menggunakan bahasa pemrograman Python. Cocok untuk mereka yang ingin memahami konsep NLP dan implementasinya menggunakan pustaka NLTK di Python.',
                'Halaman' => 502,
                'Penerbit' => 'O\'Reilly Media',
                'Tahun' => 2009,
                'Berat' => 658,
                'ISBN' => '9780596516499',
                'Lebar' => 7,
                'Panjang' => 9.19,
                'Bahasa' => 'Inggris',
                'Kategori' => 'Pemrograman',
                'Stok' => 15,
                'Akses' => 'Dapat dipinjam',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Judul' => 'Elements of Applied Stochastic Processes',
                'Author' => 'U. Narayan Bhat, Gregory K. Miller',
                'Sampul' => 'https://m.media-amazon.com/images/I/61ZRF9ACk5L.SL1360.jpg',
                'Deskripsi' => 'Buku ini menawarkan pengenalan komprehensif tentang proses stokastik dengan fokus pada aplikasi praktis di berbagai bidang. Pembahasannya mencakup teori dasar dan aplikasinya dalam masalah nyata seperti antrian, keuangan, dan reliabilitas sistem.',
                'Halaman' => 488,
                'Penerbit' => 'Wiley-Interscience',
                'Tahun' => 2002,
                'Berat' => 894,
                'ISBN' => '9780471414421',
                'Lebar' => 6.4,
                'Panjang' => 9.5,
                'Bahasa' => 'Inggris',
                'Kategori' => 'Statistika',
                'Stok' => 15,
                'Akses' => 'Dapat dipinjam',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Judul' => 'Physics for Scientists & Engineers with Modern Physics 4th Edition',
                'Author' => 'Douglas Giancoli',
                'Sampul' => 'https://m.media-amazon.com/images/I/81exf4X49AL.SL1500.jpg',
                'Deskripsi' => 'Buku ini menjelaskan fisika dengan cara yang menarik, mudah dipahami, dan relevan dengan pengalaman sehari-hari, membantu siswa belajar tanpa menyederhanakan konsep secara berlebihan.',
                'Halaman' => 1328,
                'Penerbit' => 'Pearson',
                'Tahun' => 2008,
                'Berat' => 2913,
                'ISBN' => '9780131495081',
                'Lebar' => 8.6,
                'Panjang' => 11,
                'Bahasa' => 'Inggris',
                'Kategori' => 'Sains',
                'Stok' => 15,
                'Akses' => 'Dapat dipinjam',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
